# Generated by Django 5.1.2 on 2024-11-04 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['creationDate']},
        ),
    ]
