# Generated by Django 5.1.2 on 2024-11-04 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_remove_hoodieprintdesign_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoodie',
            name='pocket',
            field=models.BooleanField(default=False),
        ),
    ]
