# Generated by Django 5.1.2 on 2024-11-04 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_hoodie_pocket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pd', 'Pendiente'), ('Ev', 'Enviado'), ('Ct', 'Completado')], default='Pendiente', max_length=2),
        ),
    ]
