# Generated by Django 5.1.2 on 2024-11-06 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoodie',
            name='PrintDesign',
            field=models.ManyToManyField(through='login.HoodiePrintDesign', to='login.printdesign'),
        ),
    ]
