# Generated by Django 5.1.2 on 2024-11-11 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_hoodie_printdesign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pd', 'Pendiente'), ('Ev', 'Enviado'), ('Ct', 'Completado'), ('Cd', 'Cancelado')], default='Pendiente', max_length=2),
        ),
    ]
