# Generated by Django 5.1.2 on 2024-11-11 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printdesign',
            name='pictureSize',
            field=models.CharField(choices=[('20x20', 'Veinteporcuarenta'), ('20x40', 'Veinteporveinte')], max_length=5),
        ),
    ]
