# Generated by Django 5.1.3 on 2024-11-19 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_alter_hoodie_hood_alter_hoodie_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoodie',
            name='details',
        ),
        migrations.AlterField(
            model_name='printdesign',
            name='picture',
            field=models.FileField(upload_to='estampados/'),
        ),
    ]
